### ISSUE TITLE
i hope i can make it 

### ISSUE THREAD

**Issue by stickylabdev** [Thaon/UDP_WIFI#1]
my plan is making simple 2d platformer multiplayer ,,,,,,,,,,,, previously i know about photon rpc etc mm hope i can

**Comment by Thaon** [comment]
Hi, this is supposed to be an educational project to teach the basics of networking and it's not a full library. You can build your networking solution starting from this but maybe something like mirror is more suited to your needs. 

Also please use more appropriate channels for these kind of requests as this is not an issue with the software.

**Comment by stickylabdev** [comment]
![image](https://user-images.githubusercontent.com/13078369/142935172-3f3d94a7-da41-4c01-9a5d-ee169d853a44.png)

i failed

> Hi, this is supposed to be an educational project to teach the basics of networking and it's not a full library. You can build your networking solution starting from this but maybe something like mirror is more suited to your needs.
> 
> Also please use more appropriate channels for these kind of requests as this is not an issue with the software.

**Comment by stickylabdev** [comment]
i build to android ,,,,,,,,,,,,,,i click host on android , and click join on laptop ,,,,,,,,,,,,,,,then the software become not responding ,,,,,,,,,,,,,,,

**Comment by stickylabdev** [comment]
i dont even know how this works https://youtu.be/4G4BCcY1AbY?t=433 , imean there is no touch input and other thing i should know ,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,need complete step by step tutorials

**Comment by stickylabdev** [comment]
the tutorial you made seems to show what you can do, and I don't know how

**Comment by Thaon** [comment]
Hi again, you are referencing an example I have on the youtube video that was produced using this library as a base. The example is not included in the final release of the code and if you bothered to read the code you would know that.

Unless you have actual issues with this project's code or are trying to post actual issues that you have found in the underlying networking structure, I would suggest that you refrain from posting here.

I am happy to provide explanations for the code if you message me privately but I am not happy helping you solve issues that are your own on the issue page of this small educational project.

As I have stated before, you should ONLY refer to this project as a baseline to learn the very basics of networked communication. 

THIS IS NOT A NETWORKING LIBRARY, IT WAS NEVER MEANT TO BE ONE.

If you are looking for far better solutions for your projects, I highly reccommend Photon or Mirror.

I wish you the very best for your endeavours but I cannot stress this enough, THIS IS NOT A PROJECT YOU SHOULD USE TO MAKE A GAME.

And absolutely is not a project you can build on any device as is and expect any result.

The provided example is not even 60 lines long and you can clearly see that it does not provide the functionality you are looking for.
